### ISSUE TITLE
login doesn't work currently

### ISSUE THREAD

**Issue by craftbrak** [craftbrak/Clever-Party-Thrower#7]
this error on login
gin error: ApolloError: Cannot read properties of null (reading 'is2faEnabled')
    at new ApolloError (index.js:26:1)
    at QueryManager.js:97:47
    at both (asyncMap.js:16:53)
    at asyncMap.js:9:72
    at new ZoneAwarePromise (zone.js:1429:1)
    at Object.then (asyncMap.js:9:24)
    at Object.next (asyncMap.js:17:49)
    at notifySubscription (module.js:132:1)
    at onNotify (module.js:176:1)
    at SubscriptionObserver.next (module.js:225:1)

this error in backend
[Nest] 20  - 05/04/2023, 8:36:36 PM   ERROR [ExceptionsHandler] Cannot read properties of null (reading 'is2faEnabled')
TypeError: Cannot read properties of null (reading 'is2faEnabled')
    at AuthService.login (/app/dist/auth/auth.service.js:79:18)
    at AuthResolver.authLogin (/app/dist/auth/auth.resolver.js:34:39)
    at async target (/app/node_modules/@nestjs/core/helpers/external-context-creator.js:74:28)
    at async Object.authLogin (/app/node_modules/@nestjs/core/helpers/external-proxy.js:9:24)

**Comment by craftbrak** [comment]
the login has been fixed and does not return an error anymore on login with the correct credentials
